### ISSUE TITLE
Conditional Requests (localeDownload-Method)

### ISSUE THREAD

**Issue by haugthom** [phrase/phrase-js#6]
How can i achieve the conditional requests with the phrase-js library?
https://developers.phrase.com/api/#overview--conditional-get-requests--http-caching

It seems the localeDownload method doesn`t offer any possibility to pass additional headers for etag or last modified.

**Comment by FRSgit** [comment]
Hey @haugthom,

Are we talking about browser or Node environment here?
The browser should take care of proper handling of request caching automatically.

**Comment by haugthom** [comment]
node environment

**Comment by FRSgit** [comment]
Thanks for this information!
So, for Node environment it's a necessity that a `fetch` implementation you provide has a built-in cache handling.
Unfortunately that's not a case with `node-fetch` library which is used in our README. But it should work properly if you replace `node-fetch` with [`make-fetch-happen`](https://www.npmjs.com/package/make-fetch-happen).

**Comment by haugthom** [comment]
As for now i have wrapped the node-fetch implementation and set the headers manually.
And i believe it would be a good option to have the possibility to set this additional headers on the **localeDownload** method.

**Frontend <--> Backend <--> Phrase**
If someone want to build a kind of a proxy (with a caching layer) in the backend for frontend, then they could share this headers between the frontend and the backend and forward them to phrase (e.g. ETags).

Maybe it works with "make-fetch-happen" as well and i can extract from the response the etags and forward them to the frontend response (if the frontend fetches a locale from the backend for frontend).
But i am not sure how i can attach the etag to the request to phrase? Maybe only the same way how i wrap the node-fetch as of today.

**And this is not a comfortable way...**

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-js) and we can take more direct action toward finding a solution.
