### ISSUE TITLE
Update remote locale with new local locale file 

### ISSUE THREAD

**Issue by ddanielcruzz** [phrase/phrase-js#9]
Hi, 

Is there a way to update a remote locale using this library? I tried using `localesApi.localeUpdate()` but I couldn't find a way to specify the local file I want to use. 

Thanks.

**Comment by theSoenke** [comment]
Hi @ddanielcruzz, the interface for the `localeUpdate` method is defined here: https://github.com/phrase/phrase-js/blob/master/src/apis/LocalesApi.ts#L72. So you should be able to update a locale with a call like this `localesApi.localeUpdate({id: "localeId", projectId: "projectId", localeUpdateParameters: {..}}`.

We are also looking into improving the documentation for this API client to make this a bit easier.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-js) and we can take more direct action toward finding a solution.
